insert into order_management.customer (fullname, registrationcode, email, telephone) values('Siim Kallas', '1001001','siim@email.ee', '56723933');
insert into order_management.customer (fullname, registrationcode, email, telephone) values('Jürgen Ligi', '1012005','jürgen@email.ee', '5675633');
insert into order_management.customer (fullname, registrationcode, email, telephone) values('Jüri Ratas', '3789346','jüri.ratas@hotmail.ee', '5283490');
insert into order_management.customer (fullname, registrationcode, email, telephone) values('Ants Laaneotsa', '9276363','a.antss@delfi.ee', '5637829');
insert into order_management.customer (fullname, registrationcode, email, telephone) values('Mihkel Muhkel', '3243242','kolepoiss123@hotmail.ee', '5682392');
insert into order_management.customer (fullname, registrationcode, email, telephone) values('Kaja Kallas', '5829383','kaja@hotmail.ee', '56373826');
insert into order_management.customer (fullname, registrationcode, email, telephone) values('Ivo Okas', '6839283','o.ivo999@hotmail.ee', '5632729');
insert into order_management.customer (fullname, registrationcode, email, telephone) values('Sven Mikser', '5829363','julmsven@gmail.com', '5234324');
insert into order_management.customer (fullname, registrationcode, email, telephone) values('Mart Helme', '2348463','ma.he@hotmail.ee', '+372 5623843');
insert into order_management.customer (fullname, registrationcode, email, telephone) values('Urmas Reinsalu', '1234556','urki@delfi.ee', '+372 5283490');
insert into order_management.customer (fullname, registrationcode, email, telephone) values('Riina Sikut', '4829033','sikuta@hotmail.ee', '5434523');
insert into order_management.customer (fullname, registrationcode, email, telephone) values('Taavi Rõivas', '2374584','külmkapitaavi@hotmail.ee', '57292300');
insert into order_management.customer (fullname, registrationcode, email, telephone) values('Andrus Ansip', '1234534','unzip@hotmail.ee', '593200');


insert into order_management.products (name, skucode, price) values('Screwdriver', 'SD37294F', 5.55);
insert into order_management.products (name, skucode, price) values('Hammer ', 'H38730X', 10.5);
insert into order_management.products (name, skucode, price) values('Backsaw', 'BS5732992X', 20);
insert into order_management.products (name, skucode, price) values('Handsaw', 'HS37294X', 12.99);
insert into order_management.products (name, skucode, price) values('Pipe wrench XL', 'PW37294XL', 45.99);
insert into order_management.products (name, skucode, price) values('Pocketknife ', 'PN37992S', 20.15);
insert into order_management.products (name, skucode, price) values('Screws 3x40, 100pcs', 'fsd4234', 6.99);
insert into order_management.products (name, skucode, price) values('Screws 4x40 100pcs', 'dfg4545', 8.99);
insert into order_management.products (name, skucode, price) values('Screws 5x40, 100pcs', 'fdsr2232', 10.99);
insert into order_management.products (name, skucode, price) values('Screws 5x70, 100pcs', 'jk73299', 15.99);
insert into order_management.products (name, skucode, price) values('Chainsaw', 'cs5782293', 599.99);
insert into order_management.products (name, skucode, price) values('Toolbox XL', 'TB4562729XL', 49.99);
insert into order_management.products (name, skucode, price) values('Toolbox L', 'TB4562729L', 36);
insert into order_management.products (name, skucode, price) values('Toolbox M', 'TB4562729M', 29.99);
insert into order_management.products (name, skucode, price) values('Electric drill 120w', 'ED239994', 150);
insert into order_management.products (name, skucode, price) values('Nuts M8, 100psc', 'n234234', 12.99);
insert into order_management.products (name, skucode, price) values('Nuts M20, 12psc', 'n45sdsd', 7.99);
insert into order_management.products (name, skucode, price) values('Stepladder 2m', 'n425dsr4', 215);

insert into order_management.orders (date, customer_id) values('2022-09-29', 1);
insert into order_management.orders (date, customer_id) values('2022-09-30', 9);
insert into order_management.orders (date, customer_id) values('2022-09-30', 10);
insert into order_management.orders (date, customer_id) values('2022-10-01', 1);
insert into order_management.orders (date, customer_id) values('2022-10-02', 2);
insert into order_management.orders (date, customer_id) values('2022-10-03', 5);
insert into order_management.orders (date, customer_id) values('2022-10-03', 7);
insert into order_management.orders (date, customer_id) values('2022-10-04', 8);
insert into order_management.orders (date, customer_id) values('2022-10-04', 9);
insert into order_management.orders (date, customer_id) values('2022-10-05', 13);
insert into order_management.orders (date, customer_id) values('2022-10-05', 2);
insert into order_management.orders (date, customer_id) values('2022-10-06', 4);
insert into order_management.orders (date, customer_id) values('2022-10-07', 6);
insert into order_management.orders (date, customer_id) values('2022-10-07', 8);
insert into order_management.orders (date, customer_id) values('2022-10-08', 9);
insert into order_management.orders (date, customer_id) values('2022-10-09', 11);
insert into order_management.orders (date, customer_id) values('2022-10-10', 13);
insert into order_management.orders (date, customer_id) values('2022-10-11', 1);
insert into order_management.orders (date, customer_id) values('2022-10-12', 2);
insert into order_management.orders (date, customer_id) values('2022-10-13', 5);
insert into order_management.orders (date, customer_id) values('2022-10-14', 10);
insert into order_management.orders (date, customer_id) values('2022-10-15', 11);
insert into order_management.orders (date, customer_id) values('2022-10-16', 12);
insert into order_management.orders (date, customer_id) values('2022-10-16', 4);
insert into order_management.orders (date, customer_id) values('2022-10-16', 7);

insert into order_management.orderlines (quantity, products_id, orders_id) values(1, 18, 1);
insert into order_management.orderlines (quantity, products_id, orders_id) values(1, 1, 1);
insert into order_management.orderlines (quantity, products_id, orders_id) values(2, 4, 1);
insert into order_management.orderlines (quantity, products_id, orders_id) values(1, 1, 2);
insert into order_management.orderlines (quantity, products_id, orders_id) values(2, 11, 2);
insert into order_management.orderlines (quantity, products_id, orders_id) values(6, 2, 3);
insert into order_management.orderlines (quantity, products_id, orders_id) values(1, 2, 4);
insert into order_management.orderlines (quantity, products_id, orders_id) values(9, 2, 5);
insert into order_management.orderlines (quantity, products_id, orders_id) values(1, 17, 6);
insert into order_management.orderlines (quantity, products_id, orders_id) values(2, 4, 7);
insert into order_management.orderlines (quantity, products_id, orders_id) values(6, 15, 7);
insert into order_management.orderlines (quantity, products_id, orders_id) values(9, 14, 7);
insert into order_management.orderlines (quantity, products_id, orders_id) values(10, 13, 7);
insert into order_management.orderlines (quantity, products_id, orders_id) values(1, 1, 7);
insert into order_management.orderlines (quantity, products_id, orders_id) values(1, 2, 7);
insert into order_management.orderlines (quantity, products_id, orders_id) values(2, 7, 8);
insert into order_management.orderlines (quantity, products_id, orders_id) values(1, 5, 9);
insert into order_management.orderlines (quantity, products_id, orders_id) values(1, 17, 10);
insert into order_management.orderlines (quantity, products_id, orders_id) values(3, 18, 11);
insert into order_management.orderlines (quantity, products_id, orders_id) values(1, 12, 12);
insert into order_management.orderlines (quantity, products_id, orders_id) values(1, 12, 13);
insert into order_management.orderlines (quantity, products_id, orders_id) values(1, 12, 14);
insert into order_management.orderlines (quantity, products_id, orders_id) values(5, 15, 15);
insert into order_management.orderlines (quantity, products_id, orders_id) values(1, 11, 15);
insert into order_management.orderlines (quantity, products_id, orders_id) values(4, 11, 16);
insert into order_management.orderlines (quantity, products_id, orders_id) values(2, 11, 17);
insert into order_management.orderlines (quantity, products_id, orders_id) values(2, 12, 18);
insert into order_management.orderlines (quantity, products_id, orders_id) values(1, 12, 19);
insert into order_management.orderlines (quantity, products_id, orders_id) values(2, 11, 19);
insert into order_management.orderlines (quantity, products_id, orders_id) values(2, 15, 19);
insert into order_management.orderlines (quantity, products_id, orders_id) values(1, 3, 19);
insert into order_management.orderlines (quantity, products_id, orders_id) values(1, 1, 19);
insert into order_management.orderlines (quantity, products_id, orders_id) values(20, 2, 20);
insert into order_management.orderlines (quantity, products_id, orders_id) values(1, 3, 20);
insert into order_management.orderlines (quantity, products_id, orders_id) values(10, 5, 20);
insert into order_management.orderlines (quantity, products_id, orders_id) values(15, 1, 21);
insert into order_management.orderlines (quantity, products_id, orders_id) values(1, 2, 21);
insert into order_management.orderlines (quantity, products_id, orders_id) values(1, 12, 22);
insert into order_management.orderlines (quantity, products_id, orders_id) values(1, 17, 23);
insert into order_management.orderlines (quantity, products_id, orders_id) values(2, 18, 24);
insert into order_management.orderlines (quantity, products_id, orders_id) values(1, 12, 25);



